#!/bin/bash
# Quick guide for setting up Neon database

echo "🗄️  Neon Database Setup Guide"
echo "=============================="
echo ""
echo "1. Create a Neon account:"
echo "   → Visit https://neon.tech"
echo "   → Sign up or log in"
echo ""
echo "2. Create a new project:"
echo "   → Click 'New Project'"
echo "   → Choose a name and region"
echo "   → Click 'Create Project'"
echo ""
echo "3. Get your connection string:"
echo "   → In your project dashboard, click 'Connection Details'"
echo "   → Copy the connection string"
echo "   → It looks like: postgresql://user:password@host.neon.tech/dbname?sslmode=require"
echo ""
echo "4. Add to .env.local:"
echo "   → Open .env.local"
echo "   → Update POSTGRES_URL with your Neon connection string"
echo ""
echo "5. Test the connection:"
echo "   → Run: pnpm db:migrate"
echo "   → This will create all necessary tables"
echo ""
echo "6. Add to Vercel:"
echo "   → Go to Vercel project → Settings → Environment Variables"
echo "   → Add POSTGRES_URL with your Neon connection string"
echo "   → Or use: vercel env add POSTGRES_URL"
echo ""
echo "✅ Once set up, your database will be ready for production!"
echo ""

